### ISSUE TITLE
Add vocabulary browsing

### ISSUE THREAD

**Issue by nichtich** [gbv/bartoc.org#16]
Browsing and searching in vocabularies such as implemented at <http://uri.gbv.de/terminology/bk/> should be added client side.

**Comment by nichtich** [comment]
Required also for metadata editor to more conveniently assign subjects. Browsing without tree-view should be enough.

**Comment by nichtich** [comment]
Required #82. Implementation should then be not too difficult like show at https://github.com/gbv/coli-conc-examples.

**Comment by stefandesu** [comment]
> Required also for metadata editor to more conveniently assign subjects.

We are currently using cocoda-sdk together with @vueform/multiselect for this. It should be enough, right?

> Browsing without tree-view should be enough.

Does this mean that we basically have Cocoda's ConceptDetail component here, pretty much exactly like implemented in https://github.com/gbv/coli-conc-examples? Should this still be a separate repository so that the component can be reused elsewhere? Should it be designed in a way that it could, at some point, replace Cocda's ConceptDetail?

I would still suggest to make a list component that also implements a tree view. These two components could then be used together. However, they need to be flexible enough so that additional features that are "too much" to be inside the components itself could be added.

**Comment by nichtich** [comment]
Implemented experimentally with version 1.1.1 but needs refactoring. In particular initialization of registries should be moved to cocoda-sdk.
