### ISSUE TITLE
Setup BARTOC Skosmos replacement

### ISSUE THREAD

**Issue by nichtich** [gbv/bartoc.org#186]
It's been asked frequently and doable, at least for a subset of vocabularies.

**Comment by VladimirAlexiev** [comment]
(from https://github.com/gbv/bartoc.org/issues/68#issuecomment-1378851797)
Could you also fix https://bartoc-skosmos.unibas.ch/en/:
- if you click on the logo, that's http://bartoc-skosmos.unibas.ch/en/ (http not https)
- which redirects to https://bartoc-skosmos.unibas.chen/, but notice the slash before en has been mangled
- which of course is a non-existing domain

**Comment by nichtich** [comment]
After closing of https://bartoc-skosmos.unibas.ch/en/ we set up a new Skosmos instance. Vocabularies are currently being imported to new domain https://skosmos.bartoc.org/.

**Comment by VladimirAlexiev** [comment]
@nichtich Do you want bugs reported about this new instance?
- all vocabs I tried have 0 concepts, but I guess that matches "currently being imported".
- There's a wide white band going down the page:
![image](https://github.com/gbv/bartoc.org/assets/536250/99e0f12b-8725-4ad1-a7e6-4210936df2ac)
This might be due to 0 concepts. Here' the offending element:
```
 <div class="sidebar-grey " style="height: calc(100% - 43px) !important">
        <div id="alphabetical-menu">
                  </div>
              </div>
```
