### ISSUE TITLE
Split vocabulary view into tabs

### ISSUE THREAD

**Issue by nichtich** [gbv/bartoc.org#85]
The vocabulary view (e.g. http://bartoc.org/en/node/18785) gets crowded, especially when we add #16. Split the view into tabs such as

* about (abstract, titles, notation, created, languages, KOS types, subjects, Links)
* Access (license, formats, access, services, publisher, address, contact, listed in, APIs)
* Content (size, search & browsing interface)
* identifiers (identifiers, namespace, notation pattern, MARCspec, PICA path, CQL key)

See also <http://uri.gbv.de/terminology/bk/> for an alternative view to be replaced by BARTOC

**Comment by stefandesu** [comment]
First implementation in dev. A few things:
- I have no good way of finding out whether a tab's content is empty or not, so there might be empty tabs at the moment.
- "URI" is currently both in "About" and in "Identifiers" (I think that's fine, but not sure what you think).
- I really don't like the top border now that we have a border around the whole tab content. We might even be able to completely remove those top borders.
- "Content" currently has basically nothing except for the extend.

Otherwise I think it's okay.

**Comment by stefandesu** [comment]
Something is broken and the vocabulary page current stays white...

**Comment by stefandesu** [comment]
Works now. 👍

**Comment by stefandesu** [comment]
@nichtich wants to move some things around, but otherwise this issue is done. 👍
